"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Error(google.protobuf.message.Message):
    """Error message definition"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LocalVarsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class GlobalVarsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class EnvironmentVarsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class ModuleVersionsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    TRACEBACK_FIELD_NUMBER: builtins.int
    THREAD_FIELD_NUMBER: builtins.int
    START_CONTEXT_FIELD_NUMBER: builtins.int
    THREAD_ID_FIELD_NUMBER: builtins.int
    IS_DAEMON_FIELD_NUMBER: builtins.int
    LOCAL_VARS_FIELD_NUMBER: builtins.int
    GLOBAL_VARS_FIELD_NUMBER: builtins.int
    ENVIRONMENT_VARS_FIELD_NUMBER: builtins.int
    MODULE_VERSIONS_FIELD_NUMBER: builtins.int
    id: builtins.str
    type: builtins.str
    message: builtins.str
    thread: builtins.str
    start_context: builtins.str
    thread_id: builtins.int
    is_daemon: builtins.bool
    @property
    def traceback(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def local_vars(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def global_vars(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def environment_vars(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def module_versions(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: builtins.str = ...,
        message: builtins.str = ...,
        traceback: collections.abc.Iterable[builtins.str] | None = ...,
        thread: builtins.str = ...,
        start_context: builtins.str = ...,
        thread_id: builtins.int = ...,
        is_daemon: builtins.bool = ...,
        local_vars: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        global_vars: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        environment_vars: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        module_versions: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["environment_vars", b"environment_vars", "global_vars", b"global_vars", "id", b"id", "is_daemon", b"is_daemon", "local_vars", b"local_vars", "message", b"message", "module_versions", b"module_versions", "start_context", b"start_context", "thread", b"thread", "thread_id", b"thread_id", "traceback", b"traceback", "type", b"type"]) -> None: ...

global___Error = Error

@typing.final
class DataPackageModule(google.protobuf.message.Message):
    """DataPackageModule message definition"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    MODULE_ID_FIELD_NUMBER: builtins.int
    MODULE_NAME_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    WAITING_TIME_FIELD_NUMBER: builtins.int
    TOTAL_TIME_FIELD_NUMBER: builtins.int
    SUB_MODULES_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    id: builtins.str
    module_id: builtins.str
    module_name: builtins.str
    running: builtins.bool
    start_time: builtins.float
    end_time: builtins.float
    waiting_time: builtins.float
    total_time: builtins.float
    message: builtins.str
    success: builtins.bool
    @property
    def sub_modules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataPackageModule]: ...
    @property
    def error(self) -> global___Error: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        module_id: builtins.str = ...,
        module_name: builtins.str = ...,
        running: builtins.bool = ...,
        start_time: builtins.float = ...,
        end_time: builtins.float = ...,
        waiting_time: builtins.float = ...,
        total_time: builtins.float = ...,
        sub_modules: collections.abc.Iterable[global___DataPackageModule] | None = ...,
        message: builtins.str = ...,
        success: builtins.bool = ...,
        error: global___Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "error", b"error", "id", b"id", "message", b"message", "module_id", b"module_id", "module_name", b"module_name", "running", b"running", "start_time", b"start_time", "sub_modules", b"sub_modules", "success", b"success", "total_time", b"total_time", "waiting_time", b"waiting_time"]) -> None: ...

global___DataPackageModule = DataPackageModule

@typing.final
class DataPackagePhase(google.protobuf.message.Message):
    """DataPackagePhase message definition"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PHASE_ID_FIELD_NUMBER: builtins.int
    PHASE_NAME_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    TOTAL_TIME_FIELD_NUMBER: builtins.int
    MODULES_FIELD_NUMBER: builtins.int
    id: builtins.str
    phase_id: builtins.str
    phase_name: builtins.str
    running: builtins.bool
    start_time: builtins.float
    end_time: builtins.float
    total_time: builtins.float
    @property
    def modules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataPackageModule]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        phase_id: builtins.str = ...,
        phase_name: builtins.str = ...,
        running: builtins.bool = ...,
        start_time: builtins.float = ...,
        end_time: builtins.float = ...,
        total_time: builtins.float = ...,
        modules: collections.abc.Iterable[global___DataPackageModule] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "id", b"id", "modules", b"modules", "phase_id", b"phase_id", "phase_name", b"phase_name", "running", b"running", "start_time", b"start_time", "total_time", b"total_time"]) -> None: ...

global___DataPackagePhase = DataPackagePhase

@typing.final
class DataPackagePhaseController(google.protobuf.message.Message):
    """DataPackagePhaseController message definition"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONTROLLER_ID_FIELD_NUMBER: builtins.int
    CONTROLLER_NAME_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    WORKERS_FIELD_NUMBER: builtins.int
    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    WAITING_TIME_FIELD_NUMBER: builtins.int
    TOTAL_TIME_FIELD_NUMBER: builtins.int
    PHASES_FIELD_NUMBER: builtins.int
    id: builtins.str
    controller_id: builtins.str
    controller_name: builtins.str
    mode: builtins.str
    workers: builtins.int
    sequence_number: builtins.int
    running: builtins.bool
    start_time: builtins.float
    end_time: builtins.float
    waiting_time: builtins.float
    total_time: builtins.float
    @property
    def phases(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataPackagePhase]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        controller_id: builtins.str = ...,
        controller_name: builtins.str = ...,
        mode: builtins.str = ...,
        workers: builtins.int = ...,
        sequence_number: builtins.int = ...,
        running: builtins.bool = ...,
        start_time: builtins.float = ...,
        end_time: builtins.float = ...,
        waiting_time: builtins.float = ...,
        total_time: builtins.float = ...,
        phases: collections.abc.Iterable[global___DataPackagePhase] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controller_id", b"controller_id", "controller_name", b"controller_name", "end_time", b"end_time", "id", b"id", "mode", b"mode", "phases", b"phases", "running", b"running", "sequence_number", b"sequence_number", "start_time", b"start_time", "total_time", b"total_time", "waiting_time", b"waiting_time", "workers", b"workers"]) -> None: ...

global___DataPackagePhaseController = DataPackagePhaseController

@typing.final
class DataPackage(google.protobuf.message.Message):
    """DataPackage message definition"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PIPELINE_ID_FIELD_NUMBER: builtins.int
    PIPELINE_NAME_FIELD_NUMBER: builtins.int
    PIPELINE_INSTANCE_ID_FIELD_NUMBER: builtins.int
    CONTROLLER_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    TOTAL_TIME_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    id: builtins.str
    pipeline_id: builtins.str
    pipeline_name: builtins.str
    pipeline_instance_id: builtins.str
    data: builtins.bytes
    running: builtins.bool
    start_time: builtins.float
    end_time: builtins.float
    total_time: builtins.float
    success: builtins.bool
    @property
    def controller(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataPackagePhaseController]: ...
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Error]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        pipeline_id: builtins.str = ...,
        pipeline_name: builtins.str = ...,
        pipeline_instance_id: builtins.str = ...,
        controller: collections.abc.Iterable[global___DataPackagePhaseController] | None = ...,
        data: builtins.bytes = ...,
        running: builtins.bool = ...,
        start_time: builtins.float = ...,
        end_time: builtins.float = ...,
        total_time: builtins.float = ...,
        success: builtins.bool = ...,
        errors: collections.abc.Iterable[global___Error] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controller", b"controller", "data", b"data", "end_time", b"end_time", "errors", b"errors", "id", b"id", "pipeline_id", b"pipeline_id", "pipeline_instance_id", b"pipeline_instance_id", "pipeline_name", b"pipeline_name", "running", b"running", "start_time", b"start_time", "success", b"success", "total_time", b"total_time"]) -> None: ...

global___DataPackage = DataPackage

@typing.final
class RequestDPandDPM(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_PACKAGE_FIELD_NUMBER: builtins.int
    DATA_PACKAGE_MODULE_FIELD_NUMBER: builtins.int
    @property
    def data_package(self) -> global___DataPackage: ...
    @property
    def data_package_module(self) -> global___DataPackageModule: ...
    def __init__(
        self,
        *,
        data_package: global___DataPackage | None = ...,
        data_package_module: global___DataPackageModule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data_package", b"data_package", "data_package_module", b"data_package_module"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data_package", b"data_package", "data_package_module", b"data_package_module"]) -> None: ...

global___RequestDPandDPM = RequestDPandDPM

@typing.final
class ReturnDPandError(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_PACKAGE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def data_package(self) -> global___DataPackage: ...
    @property
    def error(self) -> global___Error: ...
    def __init__(
        self,
        *,
        data_package: global___DataPackage | None = ...,
        error: global___Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data_package", b"data_package", "error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data_package", b"data_package", "error", b"error"]) -> None: ...

global___ReturnDPandError = ReturnDPandError
