"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import data_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ModuleServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    run: grpc.UnaryUnaryMultiCallable[
        data_pb2.RequestDPandDPM,
        data_pb2.ReturnDPandError,
    ]

class ModuleServiceAsyncStub:
    run: grpc.aio.UnaryUnaryMultiCallable[
        data_pb2.RequestDPandDPM,
        data_pb2.ReturnDPandError,
    ]

class ModuleServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def run(
        self,
        request: data_pb2.RequestDPandDPM,
        context: _ServicerContext,
    ) -> typing.Union[data_pb2.ReturnDPandError, collections.abc.Awaitable[data_pb2.ReturnDPandError]]: ...

def add_ModuleServiceServicer_to_server(servicer: ModuleServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
